name: Test Carousel Tile

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.10"
          - "3.13"
        plone:
          - "6.0-latest"
          - "6.1-latest"
    steps:
      - uses: actions/checkout@v5

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v3.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Install package
        run: |
          make install

      - name: Run Lint
        run: |
          make lint

      - name: Run tests
        run: |
          make test-ignore-warnings
